### PR TITLE
Option to use data-src-{breakpoint-name} for sizes

### PR DESCRIPTION
**Pull request by acarabott**
This lets you use data attributes to set the breakpoint image sources.

This is useful when you can't rename or predict your file names, e.g. WordPress automatically resized images where the dimensions are added as a suffix and can vary, even with the same image size specified

e.g. 
imageA-97x220.jpg
imageB-150x220.jpg

Based on approach taken by @gabrielnau

Also added to the jQuery version and included documentation and an example

### CODE REVIEW

**Comment by OleVik** [comment]
In what situations can WordPress image sizes not be predicted? In my (limited) knowledge, applying Riloadr to WordPress will work in all situations except when thumbnail-sizes are no re-generated after a change in defined image sizes, where WordPress itself reverts back to the original image size. That is, both "imageA-97x220.jpg" and "imageB-150x220.jpg" would result in the size 97x220 and 150x220 to be defined within the current WordPress image sizes (the name of the appropriate property escapes me).

**Comment by acarabott** [comment]
The two examples I gave result from the same `add_image_size()` call

``` php
add_image_size('styling_gallery', 9999, 220, false);
```

This permits images to be any width, but 220px tall, hence this result

```
imageA-97x220.jpg
imageB-150x220.jpg
```

Also, if you upload an image that is smaller than your specified size, it will return the full image when you request an image of that size, e.g.

```
imageA.jpg
```

I generally also think that it's a good option to not have to rename your image files. It's a great plugin, I just couldn't have used without this feature.

**Comment by OleVik** [comment]
That's interesting, I hope tubal implements it.

**Comment by tubalmartin** [comment]
Great suggestion! How on earth I missed that one!! :+1: 

I'll be releasing version 1.5 in the next days with this new feature.

Thanks!

**Comment by tubalmartin** [comment]
Version 1.5.0 released!

**Pull request closed without merging**
